# Use a smaller Node.js image for production
FROM node:14-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Use the 'serve' package to serve the built React app
FROM node:14-alpine
WORKDIR /app
COPY --from=build /app/dist /app


# Install 'serve' globally
RUN npm install -g serve

EXPOSE 80
CMD ["serve", "-s", "."]
