
export const currentRole = "admin"

export const Users = [
  { id: 1, name: 'John Doe', email: 'john.doe@example.com', age: 28 },
  { id: 2, name: 'Jane Smith', email: 'jane.smith@example.com', age: 35 },
  { id: 3, name: 'Alice Johnson', email: 'alice.johnson@example.com', age: 22 },
  { id: 4, name: 'Bob Williams', email: 'bob.williams@example.com', age: 30 },
  { id: 5, name: 'Emma Davis', email: 'emma.davis@example.com', age: 25 },
  { id: 6, name: 'Michael Brown', email: 'michael.brown@example.com', age: 40 },
  { id: 7, name: 'Olivia Wilson', email: 'olivia.wilson@example.com', age: 28 },
  { id: 8, name: 'Daniel Taylor', email: 'daniel.taylor@example.com', age: 33 },
  { id: 9, name: 'Sophia Martinez', email: 'sophia.martinez@example.com', age: 29 },
  { id: 10, name: 'William Jones', email: 'william.jones@example.com', age: 31 },
  { id: 11, name: 'Eva White', email: 'eva.white@example.com', age: 26 },
  { id: 12, name: 'Matthew Miller', email: 'matthew.miller@example.com', age: 37 },
  { id: 13, name: 'Ava Moore', email: 'ava.moore@example.com', age: 24 },
  { id: 14, name: 'Liam Davis', email: 'liam.davis@example.com', age: 32 },
  { id: 15, name: 'Sophie Harris', email: 'sophie.harris@example.com', age: 27 },
  { id: 16, name: 'Benjamin Turner', email: 'benjamin.turner@example.com', age: 34 },
  { id: 17, name: 'Chloe Clark', email: 'chloe.clark@example.com', age: 23 },
  { id: 18, name: 'Christopher Scott', email: 'christopher.scott@example.com', age: 36 },
  { id: 19, name: 'Zoe Taylor', email: 'zoe.taylor@example.com', age: 30 },
  { id: 20, name: 'Mia Lewis', email: 'mia.lewis@example.com', age: 29 },
  { id: 21, name: 'Jackson Smith', email: 'jackson.smith@example.com', age: 31 },
  { id: 22, name: 'Ella Hall', email: 'ella.hall@example.com', age: 28 },
  { id: 23, name: 'Ryan Allen', email: 'ryan.allen@example.com', age: 35 },
  { id: 24, name: 'Avery Adams', email: 'avery.adams@example.com', age: 26 },
  { id: 25, name: 'Grace King', email: 'grace.king@example.com', age: 33 },
  { id: 26, name: 'Aiden Brown', email: 'aiden.brown@example.com', age: 29 },
  { id: 27, name: 'Scarlett Miller', email: 'scarlett.miller@example.com', age: 38 },
  { id: 28, name: 'Carter Baker', email: 'carter.baker@example.com', age: 27 },
  { id: 29, name: 'Madison Turner', email: 'madison.turner@example.com', age: 24 },
  { id: 30, name: 'Luke Adams', email: 'luke.adams@example.com', age: 32 },
  { id: 31, name: 'Lily Turner', email: 'lily.turner@example.com', age: 25 },
  { id: 32, name: 'Nathan Mitchell', email: 'nathan.mitchell@example.com', age: 36 },
  { id: 33, name: 'Aubrey Foster', email: 'aubrey.foster@example.com', age: 29 },
  { id: 34, name: 'Ethan Wright', email: 'ethan.wright@example.com', age: 31 },
  { id: 35, name: 'Addison Hill', email: 'addison.hill@example.com', age: 28 },
  { id: 36, name: 'Andrew Martinez', email: 'andrew.martinez@example.com', age: 34 },
  { id: 37, name: 'Peyton Adams', email: 'peyton.adams@example.com', age: 27 },
  { id: 38, name: 'Hannah Moore', email: 'hannah.moore@example.com', age: 25 },
  { id: 39, name: 'Gabriel Clark', email: 'gabriel.clark@example.com', age: 30 },
  { id: 40, name: 'Zara Davis', email: 'zara.davis@example.com', age: 33 },
  { id: 41, name: 'Nicholas Baker', email: 'nicholas.baker@example.com', age: 26 },
  { id: 42, name: 'Isabella Turner', email: 'isabella.turner@example.com', age: 35 },
  { id: 43, name: 'Mason King', email: 'mason.king@example.com', age: 29 },
  { id: 44, name: 'Brooklyn Adams', email: 'brooklyn.adams@example.com', age: 31 },
  { id: 45, name: 'Samuel Scott', email: 'samuel.scott@example.com', age: 28 },
  { id: 46, name: 'Aria Turner', email: 'aria.turner@example.com', age: 34 },
  { id: 47, name: 'Dylan Lewis', email: 'dylan.lewis@example.com', age: 27 },
  { id: 48, name: 'Ava Hill', email: 'ava.hill@example.com', age: 25 },
  { id: 49, name: 'Logan Mitchell', email: 'logan.mitchell@example.com', age: 30 },
  { id: 50, name: 'Sofia Turner', email: 'sofia.turner@example.com', age: 33 },
];

